<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/DefInjected/**/*.xml key (no Keyed folder in this mod: no
  code-owned text). For each key, resolves the English text as the shipped Def's own
  label/description/tool field in Mod/Defs, dotted-path lookup, since this mod has no
  Mod/Languages/English override folder - the game's own English fallback comes straight
  from the Def. Original (source-language) text: this mod was ported from ThatRubishGamer's
  original English "A Sloth Mod" (see ATTRIBUTION.md), so Original equals English throughout;
  said once here rather than on every row.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.tools.left_claw.label"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } elseif ($p -match '^\w+$' -and $cur.SelectSingleNode($p) -eq $null -and $cur.$p -is [System.Xml.XmlElement[]]) {
            # named li lookup, e.g. tools.left_claw -> <tools><li><label>...
            $match = $cur.$p | Where-Object { $_.label -and $_.SelectSingleNode('*[local-name()="' + $rest[-1] + '"]') } | Select-Object -First 1
            $cur = $match
        } else {
            $cur = $cur.$p
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

function Resolve-ToolLabel($defsRoot, [string]$defName, [string]$sanitizedName) {
    # DefInjected sanitizes a tool's label (spaces -> underscores) into the path segment,
    # e.g. tools.left_claw.label came from a <li><label>left claw</label>.
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    foreach ($tool in $node.SelectNodes('tools/li')) {
        if (($tool.label -replace ' ', '_') -eq $sanitizedName) { return $tool.label }
    }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod ports ThatRubishGamer's original")
[void]$out.AppendLine("English ``A Sloth Mod`` (see ATTRIBUTION.md); there is no non-English source text.")
[void]$out.AppendLine()
[void]$out.AppendLine("No ``Mod/Languages/Keyed`` folder: this mod has no code-owned text, only DefInjected fields.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree at HEAD e280013.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = $null
        if ($key -match '^(\w+)\.tools\.(\w+)\.label$') {
            $en = Resolve-ToolLabel $defsRoot $Matches[1] $Matches[2]
        } else {
            $en = Resolve-DefField $defsRoot $key
        }
        $orig = $en
        if ($null -eq $orig) { $orig = '*(not found - check by hand)*' }
        if ($null -eq $en) { $en = '*(not found - check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
